# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_classes_pb2 as data__classes__pb2


class masterStub(object):
    """Registry Server RPCs"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.register = channel.unary_unary(
            "/data_classes.master/register",
            request_serializer=data__classes__pb2.RegisterRequest.SerializeToString,
            response_deserializer=data__classes__pb2.RegisterResponse.FromString,
        )


class masterServicer(object):
    """Registry Server RPCs"""

    def register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_masterServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "register": grpc.unary_unary_rpc_method_handler(
            servicer.register,
            request_deserializer=data__classes__pb2.RegisterRequest.FromString,
            response_serializer=data__classes__pb2.RegisterResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "data_classes.master", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class master(object):
    """Registry Server RPCs"""

    @staticmethod
    def register(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/data_classes.master/register",
            data__classes__pb2.RegisterRequest.SerializeToString,
            data__classes__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
