# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_classes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12\x64\x61ta_classes.proto\x12\x0c\x64\x61ta_classes":\n\x0fRegisterRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x19\n\x11registration_type\x18\x02 \x01(\t"\xba\x01\n\x10RegisterResponse\x12\x13\n\x0bnum_mappers\x18\x01 \x01(\x05\x12\x14\n\x0cnum_reducers\x18\x02 \x01(\x05\x12\x0c\n\x04task\x18\x03 \x01(\t\x12\x17\n\x0finput_directory\x18\x04 \x01(\t\x12\x18\n\x10output_directory\x18\x05 \x01(\t\x12\x1e\n\x16intermediate_directory\x18\x06 \x01(\t\x12\x1a\n\x12worker_sequence_id\x18\x07 \x01(\x05"\x1b\n\x0cSimpleString\x12\x0b\n\x03str\x18\x01 \x01(\t2U\n\x06master\x12K\n\x08register\x12\x1d.data_classes.RegisterRequest\x1a\x1e.data_classes.RegisterResponse"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "data_classes_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _REGISTERREQUEST._serialized_start = 36
    _REGISTERREQUEST._serialized_end = 94
    _REGISTERRESPONSE._serialized_start = 97
    _REGISTERRESPONSE._serialized_end = 283
    _SIMPLESTRING._serialized_start = 285
    _SIMPLESTRING._serialized_end = 312
    _MASTER._serialized_start = 314
    _MASTER._serialized_end = 399
# @@protoc_insertion_point(module_scope)
